apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-nodejs-example
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: angular-nodejs-example.dev.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angular-nodejs-example
                port:
                  number: 80
