apiVersion: v1
kind: Service
metadata:
  name: angular-nodejs-example
  namespace: dev
  labels:
    app: angular-nodejs-example
spec:
  type: ClusterIP
  selector:
    app: angular-nodejs-example
  ports:
    - name: http
      port: 80
      targetPort: 3080
